# 必须包含二级目录名，末尾记得加斜杠
baseURL = 'https://bitcatMeng.github.io/feifan_blog/'
languageCode = 'en-us'
title = '非凡哥编程'
theme = "PaperMod"

[params]
    env = "production" # 生产环境
    showCodeCopyButtons = true # 显示代码复制按钮
    displayFullContent = false # 列表页不显示全文
